name: Build Documentation

on:
  push: {branches: [main]} # pushes to main
  pull_request: {} # all PRs

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build docs
      run: |
        make html SPHINXOPTS="-W --keep-going"

    - uses: actions/upload-artifact@v4
      with:
        path: _build/html
