name: Build Documentation

on:
  push: {branches: [main]} # pushes to main
  pull_request: {} # all PRs
  schedule: [cron: '0 12 * * 3'] # every Wednesday at noon

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build docs
      run: |
        make html SPHINXOPTS="-W --keep-going"

    - uses: actions/upload-artifact@v4
      with:
        path: docs/_build/html
